In [2]:
import tensorflow as tf

In [3]:
sess = tf.InteractiveSession()

In [4]:
tf.zeros(2)

<tf.Tensor 'zeros:0' shape=(2,) dtype=float32>

In [5]:
a =tf.zeros(2)
a.eval()

array([0., 0.], dtype=float32)

In [6]:
b = tf.fill((2, 2), value= 5.)
b.eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [7]:
c = tf.constant(3)
c.eval()

3

In [9]:
tf.random_normal((2, 2), mean=0, stddev=1).eval()

#tf.truncated_normal()

array([[-0.45501375,  0.06428355],
       [-0.0641296 ,  0.01702549]], dtype=float32)

In [10]:
tf.random_uniform((2, 2), minval=-2, maxval=2).eval()

array([[-1.5427084 ,  0.42875195],
       [-0.9002209 , -1.3152022 ]], dtype=float32)

In [11]:
c = tf.ones((2, 2))
d = tf.ones((2, 2))

e = c + d
e.eval()

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [12]:
c = tf.fill((2,2), 2.)
d = tf.fill((2,2), 7.)
e = c * d
e.eval()


array([[14., 14.],
       [14., 14.]], dtype=float32)

In [14]:
a = tf.eye(4)
a.eval()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [15]:
r = tf.range(1, 5, 1)
r.eval()

array([1, 2, 3, 4], dtype=int32)

In [16]:
d = tf.diag(r)
d.eval()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)

In [18]:
tf.ones((2, 3)).eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [21]:
tf.matrix_transpose(tf.ones((2, 3))).eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [23]:
a = tf.ones((2, 3))
b = tf.ones((3, 4))
tf.matmul(a, b).eval()

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

In [24]:
a = tf.ones((2, 2), dtype=tf.int32)
a.eval()

array([[1, 1],
       [1, 1]], dtype=int32)

In [27]:
tf.cast(a, tf.float32).eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [29]:
a = tf.ones(8)
a.eval()

array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [31]:
tf.reshape(a, (4, 2)).eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [33]:
tf.reshape(a, (2, 2, 2)).eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [35]:
a = tf.ones(2, 2)
a.get_shape()

TensorShape([Dimension(2)])

In [37]:
a.eval()

array([1., 1.])

In [38]:
b = tf.expand_dims(a, 0)
b.get_shape()

TensorShape([Dimension(1), Dimension(2)])

In [40]:
b.eval()

array([[1., 1.]])

In [41]:
c = tf.expand_dims(a, 1)
c.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [42]:
c.eval()

array([[1.],
       [1.]])

In [44]:
d = tf.squeeze(b)
d.get_shape()

TensorShape([Dimension(2)])

In [45]:
d.eval()

array([1., 1.])

In [46]:
a = tf.ones((2, 2))
a.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [47]:
b = tf.range(0, 2, 1, dtype=tf.float32)
b.eval()

array([0., 1.], dtype=float32)

In [48]:
c = a + b
c.eval()

array([[1., 2.],
       [1., 2.]], dtype=float32)

In [49]:
# Notice that the vector b is added to every row of matrix a . Notice another subtlety; we
# explicitly set the dtype for b . If the dtype isn’t set, TensorFlow will report a type error.
# Let’s see what would have happened if we hadn’t set the dtype (Example 2-19).
# Example 2-19. TensorFlow doesn’t perform implicit type casting
b = tf.range(0, 2, 1)
b.eval()


array([0, 1], dtype=int32)

In [50]:
c = a + b

TypeError: Input 'y' of 'Add' Op has type int32 that does not match type float32 of argument 'x'.

In [51]:
a = tf.constant(3)
b = tf.constant(4)
c = a + b
c

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [52]:
c.eval()

7

In [53]:
tf.get_default_graph()

In [54]:
sess = tf.Session()
a = tf.ones((2, 2))
b = tf.matmul(a, a)
b.eval(session=sess)

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [55]:
sess.run(b)

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [56]:
a = tf.Variable(tf.ones((2, 2)))
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>

In [57]:
a.eval()

FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value Variable
	 [[node Variable (defined at <ipython-input-56-f595cae7fa1a>:1) ]]
	 [[Variable/_97]]
  (1) Failed precondition: Attempting to use uninitialized value Variable
	 [[node Variable (defined at <ipython-input-56-f595cae7fa1a>:1) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'Variable':
  File "/home/roozbehdz/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/roozbehdz/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 583, in start
    self.io_loop.start()
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 153, in start
    self.asyncio_loop.run_forever()
  File "/home/roozbehdz/anaconda3/lib/python3.7/asyncio/base_events.py", line 538, in run_forever
    self._run_once()
  File "/home/roozbehdz/anaconda3/lib/python3.7/asyncio/base_events.py", line 1782, in _run_once
    handle._run()
  File "/home/roozbehdz/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 787, in inner
    self.run()
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-56-f595cae7fa1a>", line 1, in <module>
    a = tf.Variable(tf.ones((2, 2)))
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 259, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 220, in _variable_v1_call
    shape=shape)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 198, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2511, in default_variable_creator
    shape=shape)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 263, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1568, in __init__
    shape=shape)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 1728, in _init_from_args
    name=name)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/state_ops.py", line 79, in variable_op_v2
    shared_name=shared_name)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 1609, in variable_v2
    shared_name=shared_name, name=name)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/roozbehdz/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


In [58]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
a.eval(session=sess)

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [60]:
sess.run(a.assign(tf.zeros((2, 2))))

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [61]:
sess.run(a)

array([[0., 0.],
       [0., 0.]], dtype=float32)